In [6]:
import torch_geometric as pyg
from torch_geometric import nn, datasets
from torch_geometric.loader import DataLoader
from torch import optim

In [2]:
data = datasets.MovieLens100K('./data')

In [37]:
movies = next(iter(data))['movie']
users = next(iter(data))['user']
edges = next(iter(data))['user', 'rates', 'movie']

In [40]:
movies.x.shape

torch.Size([1682, 18])

In [41]:
users.x.shape

torch.Size([943, 24])

In [61]:
edges.edge_index[1,:10]

tensor([ 0,  1,  2,  3,  4,  6,  7,  8, 10, 12])

In [54]:
edges.rating

tensor([5, 3, 4,  ..., 3, 3, 3])

In [63]:
edges.edge_label_index[1,:10]

tensor([ 5,  9, 11, 13, 16, 19, 22, 23, 26, 30])